### ISSUE TITLE
types.installAllDependencies not found

### ISSUE THREAD

**Issue by Morphexe** [jvitor83/types-autoinstaller#12]
I just installed the package from the store and the command is not found via the console.

Also, no changes are made when saving the package.json, either editing directly and saving or via npm / yarn install with save option.

Any idea what could be possibly doing this?

**Comment by tamj0rd2** [comment]
Can you give these details please?

- Operating system
- Version of npm/yarn
- Version of VS Code

Are you getting any errors in the developer console (Help > Toggle developer tools)? I've tested this with vscode version 1.15.1 and am not having any issues.

**Comment by tamj0rd2** [comment]
@jvitor83 The stack trace is saying `Cannot find module 'lodash'` which I used in my last PR.

Would you be able to run `npm install` to install all the new deps and then publish it again to see if it works?

**Comment by tamj0rd2** [comment]
My fault, I think I put lodash into the wrong section of package.json. I'll fix this now.

**Comment by Morphexe** [comment]
The strange thing is I pulled from the repo, and debugged it, and the repo worked perfectly fine =)
Anyway glad to see it fixed.

Thank you for the quick reply =)

**Comment by jvitor83** [comment]
Yes. I tested it, and it worked at debugging too.
Anyway, i will merge and release this fix today.
