### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Cologler** [jvitor83/types-autoinstaller#7]
Can you add some docs in README to show how it detect the package (by watch `package.json` or else) ?

**Comment by jvitor83** [comment]
At https://github.com/jvitor83/types-autoinstaller/blob/master/src/extension.ts#L56 you can see how.
It is using a VSCode feature `createFileSystemWatcher` and `onDidChange`.

**Comment by Cologler** [comment]
@jvitor83 Does that mean anyone want to know how to activate the extension, they need to read the source code (not just the readme.md) ?

**Comment by tamj0rd2** [comment]
Isn't this already answered in the README though?

> Any time you save either package.json or bower.json the typings packages will be installed/uninstalled automatically in the background.

> To initially install all types of a project, open the Command Palette with F1 and type in Types: Install definitions for all dependencies, press Enter to select it.

But if you want to understand what's actually happening in the background you'll need to have a look at the source code. As long as you have a `package.json` in your project, the extension will activate.

**Comment by Cologler** [comment]
@jvitor83 @tamj0rd2 Seems like I ignore the line. Sorry.
