### ISSUE TITLE
Type definition files downloads cannot synchronize with commands

### ISSUE THREAD

**Issue by OshotOkill** [jvitor83/types-autoinstaller#9]
I found out that appropriate `.d.ts` files cannot be automatically downloaded by a single command `npm i xxx`. You have to type the `npm i xxx` again.

![a](https://user-images.githubusercontent.com/6079112/28952839-87c1f1a2-7906-11e7-9d16-7963f5727221.gif)

I'm on Windows 10 15063.502

**Comment by tamj0rd2** [comment]
Which version of npm are you using?

**Comment by OshotOkill** [comment]
node v8.2.1
npm  v5.3.0

**Comment by OshotOkill** [comment]
Also get the same problem on MacOS 10.12.6

Node 8.3.0
Npm 5.3.0

 
![kapture 2017-08-11 at 22 16 17](https://user-images.githubusercontent.com/6079112/29217381-300788e4-7ee4-11e7-8f11-f06e5eb28bdf.gif)

**Comment by tamj0rd2** [comment]
Looking into this now

**Comment by tamj0rd2** [comment]
This is something to do with the way vscode's FileSystemWatcher works. If you were to edit package.json manually it'd work. However, when npm/yarn modifies the file, vscode doesn't pick up any of the new changes until the next time it gets changed, which is weird. I'll keep an eye out for a workaround.

**Comment by OshotOkill** [comment]
Thanks. Maybe the issue should be sent to the vscode team to figure it out.

**Comment by tamj0rd2** [comment]
I've just realised this can be worked around using a setTimeout. I'll submit a PR for this today or tomorrow
